version: '3.8'
services:
  app:
    build: 
      context: .
      args:
        - TELEGRAM_API_ID=${TELEGRAM_API_ID}
        - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
        - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_PHONE=+380662468494
      - CHAT_LINK=-1002239405289
      - TELEGRAM_REPORT_CHAT_ID=-1002624153500
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - .:/app
      - ./sessions:/app/sessions
      - ./data:/app/data
      - ./logs:/app/logs
