version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - .:/app
      - ./sessions:/app/sessions
      - ./data:/app/data
      - ./logs:/app/logs
